<?php namespace ProcessWire;


class InputfieldCroppableImage4 extends InputfieldImage {

    public static function getModuleInfo() {
        return array(
            'title'    => 'Croppable Image 4 (Inputfield)',
            'summary'  => 'One or more image uploads (optional predefined crops)',
            'author'   => 'Horst Nogajski',
            'version'  => '2.0.1',
            'requires' => 'ProcessWire>=3.0.132, PHP>=7.0.0, FieldtypeCroppableImage4>=2.0.1',
            'icon'     => 'crop'
        );
    }

    protected $textCollection = array();

    protected function getText($key, $default = '(N/A)') {
        if(!isset($this->textCollection['CroppableImage4TextCollectionVersion'])) {
            require_once(__DIR__ . '/../lang/CroppableImage4TextCollection.php');
            $c = new CroppableImage4TextCollection();
            $this->textCollection = $c->combine($this->textCollection);
        }
        return isset($this->textCollection[$key]) ? $this->textCollection[$key] : $default;
    }

    public function __construct() {
        parent::__construct();
        require_once(dirname(__FILE__) . '/../classes/CroppableImage4CropSettings.class.php');
        require_once(dirname(__FILE__) . '/../classes/CroppableImage4Helpers.class.php');
    }

    public function init() {
        parent::init();
        // default settings
        $this->set('cropSetting', '');
        $this->set('hideCoreFeatures', "-All\nCrop\nFocus\nActions");
        // we definetly need this to be displayed, as it contains the cropLinks !!
        $this->set('useImageEditor', 1);
        $this->labels = array_merge($this->labels, array(
            'caiName' => 'Name'
        ));
    }

    // don't let out the parent modules assets and wrapper !!
    public function renderReady(Inputfield $parent = null, $renderValueMode = false) {
        parent::renderReady($parent, $renderValueMode);
        $this->wire('modules')->loadModuleFileAssets('InputfieldImage');
        $this->addClass('InputfieldImage', 'wrapClass');
        return true;
    }

//    public function ___render() {
//        $out = parent::___render();
//        return $out;
//    }

    protected function hideCoreImageFeatures() {
        $a = explode("\n", trim($this->get('hideCoreFeatures')));
        $All = $Crop = $Focus = $Actions = false;
        foreach($a as $line) {
            if('all' == substr(mb_strtolower(trim($line)), 0, 3)) {
                $All = true;
                break;
            } elseif('crop' == substr(mb_strtolower(trim($line)), 0, 4)) {
                $Crop = true;
            } elseif('focus' == substr(mb_strtolower(trim($line)), 0, 5)) {
                $Focus = true;
            } elseif('action' == substr(mb_strtolower(trim($line)), 0, 6)) {
                $Actions = true;
            }
        }
        $thisFieldname = '.Inputfield_' . $this->hasField->name;
        $style = "\n<style>\n";
            if($All) $style .= "{$thisFieldname} .InputfieldImageEdit__buttons button, {$thisFieldname} .InputfieldFileActionSelect { display: none !important; }\n";
            if(!$All && $Crop) $style .= "{$thisFieldname} .InputfieldImageEdit__buttons .InputfieldImageButtonCrop  { display: none !important; }\n";
            if(!$All && $Focus) $style .= "{$thisFieldname} .InputfieldImageEdit__buttons .InputfieldImageButtonFocus  { display: none !important; }\n";
            if(!$All && $Actions) $style .= "{$thisFieldname} .InputfieldFileActionSelect { display: none !important; }\n";
            $style .= "{$thisFieldname} .InputfieldImageEdit__info { display: none !important; }\n";
            $style .= "{$thisFieldname} .InputfieldImageEdit__name span { cursor: default; }\n";
            $style .= "{$thisFieldname} .InputfieldImageEdit__imagewrapper .detail-upload { visibility: hidden !important; }\n";
        $style .= "</style>\n";
        return $style;
    }


    protected function ___renderButtons($pagefile, $id, $n) {
        $out = parent::___renderButtons($pagefile, $id, $n);
        $cropLinks = $this->getCropLinks($pagefile);
        if($cropLinks) {
            $out = $this->hideCoreImageFeatures() .
                   "<div class='croppableImageButtons'><p>" . $this->getText('predefinedCrops') . "</p>" .
                   $cropLinks . "</div>" . $out;
        }
        return $out;
    }

    /**
     * Returns the croplinks HTML string or boolean false. Depending on field
     * configuration.
     *
     * @param Pagefile $pagefile
     * @return mixed (string|bool false)
     *
     */
    private function getCropLinks($pagefile) {

        $cropSettings = new CroppableImage4CropSettings($this->cropSetting);

        // no crops, no glory
        if(!count($cropSettings->items)) return false;

        $baseCropUrl = $this->config->urls->admin . "page/" . ProcessCroppableImage4::adminPageName . "/";
        $upscaling = CroppableImage4Helpers::getGlobalImageSetting('upscaling');  // setting 1x holen reicht :)
        $templateName = $pagefile->page->template->name;
        $imageWidth = $pagefile->width;
        $imageHeight = $pagefile->height;
        $adminThumb = $this->getAdminThumb($pagefile);
        $jsCropInfo = array();
        $out = '';

        // crop previews
//        $w = $pagefile->width;
//        $h = $pagefile->height;
//        $adminThumb['attr']['data-grid-x'] = ceil(140 / $w * $h);
//        $adminThumb['attr']['data-grid-y'] = ceil(140 / $h * $w);

        /** @var integer $pages_id, Page ID for crop links, defaulting to 0 */
        $pages_id = 0;
        /** @var [ProcessPageEdit|ProcessUser|ProcessProfile] $process, Mixed processes maybee there are more */
        $process = $this->wire('process');
        if(method_exists($process, 'getPage')) {
            $editPage = $process->getPage();
            if($editPage->id) $pages_id = $editPage->id;
        }
        $pages_id = $pages_id ? $pages_id : (int)$this->input->get->id;

        foreach($cropSettings->items as $cropSetting) {

            if(!$cropSetting->isTemplateAllowed($templateName)) continue;

            $warning = false;
            $suffix = $this->sanitizer->name($cropSetting->name);
            $imageTooSmall = $cropSetting->width > $imageWidth || $cropSetting->height > $imageHeight;

            // Upscaling not allowed ($config setting)
            if($imageTooSmall && $upscaling === false) {
                $warning = sprintf($this->getText('cropSetting_toLarge'),
                    "{$cropSetting->width}x{$cropSetting->height}",
                    "{$imageWidth}x{$imageHeight}");
            }

            // CropUrl with additional parameters
            $cropUrlWithParams = $baseCropUrl . '?' . http_build_query(array(
                'filename' => $pagefile->basename,
                'suffix' => $suffix,
                'width' => $cropSetting->width,
                'height' => $cropSetting->height,
                'pages_id' => $pages_id,
                'field' => mb_strtolower($this->name),  // TODO: name to lowercase ??? N: Yes! ;-)  ()
                'modal' => 1
                ));

            // HTML attributes
            $attr = array('data-suffix' => $suffix);

            // Upscaling not allowed ($config setting)
            if($warning) {
                $attr['data-croppable'] = 0;
                $attr['class'] = 'crop-button ui-state-error';
                $attr['data-warning'] = $warning;
            } else {
                $attr['data-croppable'] = 1;
                $attr['class'] = 'crop-button ui-button ui-button pw-modal-large pw-modal ui-state-default';
                $attr['href'] = $cropUrlWithParams;
                $attr['target'] = '_blank';
                $attr['data-image'] = $pagefile->getCrop4($suffix)->url;
                $attr['data-width'] = $cropSetting->width;
            }

            // Dimensions per crop
            $jsCropInfo['crops'][$suffix] = array(
                'width' => $cropSetting->width,
                'height' => $cropSetting->height,
            );

            $thumbnailOptions = array(
                'quality'     => 80,
                'sharpening'  => 'soft',
                'webpAdd'     => false,
                'suffix'      => ''
            );
            $out .= "<a href='$cropUrlWithParams' " . CroppableImage4Helpers::arrayToHtmlAttr($attr) . ">";
            $out .= "<i class='fa "  . ($warning ? 'fa-exclamation-circle' : 'fa-crop') . "'></i> ";
            $out .= "<span>";
            $out .= $cropSetting->name;
            $out .= "</span> ";
            $out .= $warning ? '' : " <img src='{$pagefile->getCrop4($suffix)->height(48, $thumbnailOptions)->url}?nc={$pagefile->mtime}' alt='' />";  // added a small indicator thumb to each crop-button
            $out .= "</a>";

        }

        // translatable
        $jsCropInfo['text'] = array(
            'edit' => $this->getText('jsCropInfo_edit'),
            'empty_fields' => $this->getText('jsCropInfo_emptyFields')
        );

//        $jsCropInfo['grid'] = array(
//            'x' => $adminThumb['attr']['data-grid-x'],
//            'y' => $adminThumb['attr']['data-grid-y'],
//        );

        $this->config->js('CroppableImage4', $jsCropInfo);

        return $out ? "<div class='cropLinks'>{$out}</div>" : false;
    }


	        protected function ___buildTooltipData($pagefile) {

		        $data = array(
                    array(
                        $this->labels['caiName'],
                        "{$pagefile->name}"
                    ),
                    array(
				        $this->labels['dimensions'],
				        "{$pagefile->width}x{$pagefile->height}"
			        ),
			        array(
				        $this->labels['filesize'],
				        str_replace(' ', '&nbsp;', $pagefile->filesizeStr)
			        ),
			        array(
				        $this->labels['variations'],
				        count($this->getPagefileVariations($pagefile))
			        )
		        );

		        if(strlen($pagefile->description)) {
			        $data[] = array(
				        $this->labels['description'],
				        "<span class='fa fa-check'></span>"
			        );
		        }

		        if($this->useTags && strlen($pagefile->tags)) {
			        $data[] = array(
				        $this->labels['tags'],
				        "<span class='fa fa-check'></span>"
			        );
		        }

		        return $data;
	        }


    public function ___getConfigInputfields() {
        $inputfields = parent::___getConfigInputfields();

        $field = $this->modules->get("InputfieldTextarea");
        $field->attr('name+id', 'cropSetting');
        $field->attr('value', (string)$this->get('cropSetting'));
        $field->label = $this->getText('fieldCropSetting_Label');
        $field->description = $this->getText('fieldCropSetting_Description');
        $inputfields->add($field);

        $field = $this->modules->get("InputfieldTextarea");
        $field->attr('name+id', 'hideCoreFeatures');
        $field->attr('value', (string)$this->get('hideCoreFeatures'));
        $field->label = $this->getText('fieldHideCoreFeatures_Label');
        $field->description = trim($this->getText('fieldHideCoreFeatures_Description')) . "\n -All (" . trim($this->getText('fieldHideCoreFeatures_DescriptionPart2')) . ")\nCrop\nFocus\nActions";
        $field->collapsed = Inputfield::collapsedYes;
        $inputfields->add($field);

        return $inputfields;
    }

}
